<?php

namespace Sprint\Migration;


class Logistic20210617100050 extends Version
{
    protected $description = "";

    protected $moduleVersion = "3.17.2";

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();
        $iblockId = $helper->Iblock()->getIblockIdIfExists('main_catalog', '1c_catalog');
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: вес',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_WEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Weight',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: объем',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_VOLUME',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Volume',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: длина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_LENGTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Length',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: ширина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_WIDTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Width',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: высота',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_HEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Height',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Индивидуальная упаковка: штрихкод',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'INDIVIDUAL_PACKAGE_BARCODE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'Barcode',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: количество',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_QUANTITY',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Quantity',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: вес',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_WEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Weight',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: объем',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_VOLUME',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Volume',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая  упаковка: длина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_LENGTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Length',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: ширина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_WIDTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Width',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: высота',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_HEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Height',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Групповая упаковка: штрихкод',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'GROUP_PACKAGE_BARCODE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'GroupPack_Barcode',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: количество',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_QUANTITY',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Quantity',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: вес',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_WEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Weight',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: объем',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_VOLUME',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Volume',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: длина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_LENGTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Length',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: ширина',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_WIDTH',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Width',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: высота',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_HEIGHT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Height',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Транспортная упаковка: штрихкод',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'TRANSPORT_PACKAGE_BARCODE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TransportPack_Barcode',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->UserOptions()->saveElementForm($iblockId, array (
  'Элемент|edit1' => 
  array (
    'ID' => 'ID',
    'DATE_CREATE' => 'Создан',
    'TIMESTAMP_X' => 'Изменен',
    'ACTIVE' => 'Активность',
    'ACTIVE_FROM' => 'Начало активности',
    'ACTIVE_TO' => 'Окончание активности',
    'NAME' => 'Название',
    'XML_ID' => 'Внешний код',
    'CODE' => 'Символьный код',
    'IBLOCK_ELEMENT_PROPERTY' => 'Значения свойств',
    'IBLOCK_ELEMENT_PROP_VALUE' => 'Значения свойств',
    'PROPERTY_2534' => 'Ссылки на обзор',
    'PROPERTY_VES_BRUTTO' => 'Вес брутто',
    'PROPERTY_VES_NETTO' => 'Вес нетто',
    'PROPERTY_OBEM' => 'Объем',
    'PROPERTY_DLINA' => 'Длина',
    'PROPERTY_CML2_ARTICLE' => 'Артикул',
    'PROPERTY_CML2_BASE_UNIT' => 'Базовая единица',
    'PROPERTY_MORE_PHOTO' => 'Картинки',
    'PROPERTY_YOUTUBE_VIDEO' => 'Youtube видео',
    'PROPERTY_REVIEWS' => 'Обзоры',
    'PROPERTY_POPULARITY' => 'Популярность',
    'PROPERTY_CML2_MANUFACTURER' => 'Производитель',
    'PROPERTY_CML2_TRAITS' => 'Реквизиты',
    'PROPERTY_CML2_TAXES' => 'Ставки налогов',
    'PROPERTY_FILES' => 'Файлы',
    'PROPERTY_CML2_ATTRIBUTES' => 'Характеристики',
    'PROPERTY_SHIRINA' => 'Ширина',
    'PROPERTY_CML2_BAR_CODE' => 'ШтрихКод',
    'PROPERTY_VYSOTA' => 'Высота',
    'PROPERTY_KOLICHESTVO_V_UPAKOVKE' => 'Количество в упаковке',
    'PROPERTY_DOPOLNITELNOE_IZOBRAZHENIE' => 'Дополнительное изображение',
    'PROPERTY_OSNOVNOE_IZOBRAZHENIE' => 'Основное изображение',
    'PROPERTY_DOPOLNITELNYE_IZOBRAZHENIYA' => 'Дополнительные изображения',
    'PROPERTY_GARANTIYA_MES' => 'Гарантия',
    'PROPERTY_2252' => 'Новинка',
    'PROPERTY_SERIYA' => 'Серия',
    'PROPERTY_MATERIAL_KORPUSA' => 'Материал корпуса',
    'PROPERTY_SREDN_NOMIN_SROK_SLUZHBY_CH' => 'Средн. номин. срок службы',
    'PROPERTY_DLINA_MM' => 'Длина',
    'PROPERTY_DIAMETR_MM' => 'Диаметр',
    'PROPERTY_UGOL_SVETOVOGO_PUCHKA_' => 'Угол светового пучка',
    'PROPERTY_TSVETOVAYA_TEMPERATURA_K' => 'Цветовая температура',
    'PROPERTY_KATEGORIYA_TSVETNOSTI_SVETA' => 'Категория цветности света',
    'PROPERTY_INDEKS_TSVETOPEREDACHI_RA' => 'Индекс цветопередачи (Ra)',
    'PROPERTY_SVETOVOY_POTOK_LM' => 'Световой поток',
    'PROPERTY_NOMIN_NAPRYAZHENIE_V' => 'Номин. напряжение',
    'PROPERTY_MOSHCHNOST_LAMPY_VT' => 'Мощность лампы',
    'PROPERTY_TSOKOL' => 'Цоколь',
    'PROPERTY_FORMA_LAMPY_KOLBY' => 'Форма лампы/колбы',
    'PROPERTY_STEPEN_ZASHCHITY_IP' => 'Степень защиты (IP)',
    'PROPERTY_DIAPAZON_VKHODNOGO_PEREMENNOGO_NAPRYAZHENIYA_V' => 'Диапазон входного переменного напряжения',
    'PROPERTY_UPRAVLENIE_IZMENENIE_TSVETOVOY_TEMPERATUROY' => 'Управление (изменение) цветовой температурой',
    'PROPERTY_NARUZH_DIAMETR_MM' => 'Наруж. диаметр',
    'PROPERTY_VYSOTA_GLUBINA_MM' => 'Высота/глубина',
    'PROPERTY_TSVET_KORPUSA' => 'Цвет корпуса',
    'PROPERTY_SPOSOB_MONTAZHA' => 'Способ монтажа',
    'PROPERTY_TIP_STEKLA_KOLBY' => 'Тип стекла колбы',
    'PROPERTY_RAZMER' => 'Размер',
    'PROPERTY_MONTAZHNYY_RAZMER' => 'Монтажный размер',
    'PROPERTY_PODKHODIT_DLYA_PODVESNOGO_MONTAZHA' => 'Подходит для подвесного монтажа',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_MM_DLYA_MEBELNYKH_SVETIL' => 'Класс пожаробезопасности "ММ" для мебельных светильников',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_M_DLYA_MEBELNYKH_SVETILN' => 'Класс пожаробезопасности "М" для мебельных светильников',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_F_DLYA_VSTRAIVAEMYKH_SVE' => 'Класс пожаробезопасности "F" для встраиваемых светильников',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_D' => 'Класс пожаробезопасности "D"',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_FF' => 'Класс пожаробезопасности "FF"',
    'PROPERTY_KLASS_POZHAROBEZOPASNOSTI_F' => 'Класс пожаробезопасности "F"',
    'PROPERTY_ZASHCHITA_OT_UDARA_MYACHOM' => 'Защита от удара мячом',
    'PROPERTY_KLASS_ZASHCHITY' => 'Класс защиты',
    'PROPERTY_DOSTUPNY_DOPOLNIT_SVETOTEKHNICHESKIE_AKSESSUARY' => 'Доступны дополнит. светотехнические аксессуары',
    'PROPERTY_VYKHOD_SVETOVOGO_POTOKA' => 'Выход светового потока',
    'PROPERTY_PERFORIROVANNYY_OTRAZHATEL' => 'Перфорированный отражатель',
    'PROPERTY_OTRAZHATEL_REFLEKTOR' => 'Отражатель (рефлектор)',
    'PROPERTY_PERFORIROVANNYY_RASTR_RESHETKA' => 'Перфорированный растр/решетка',
    'PROPERTY_PODKHODIT_DLYA_RABOCHEGO_MESTA_S_MONITOROM' => 'Подходит для рабочего места с монитором',
    'PROPERTY_ELEKTRICHESKOE_PODKLYUCHENIE_CHEREZ_SHTEPSELNYE_RA' => 'Электрическое подключение через штепсельные разъемы',
    'PROPERTY_PODKHODIT_DLYA_PROKLADKI_SKVOZNOY_PROVODKI' => 'Подходит для прокладки сквозной проводки',
    'PROPERTY_RAZDELNOE_UPRAVLENIE_PRYAMYM_I_OTRAZHENNYM_SVETOM' => 'Раздельное управление прямым и отраженным светом',
    'PROPERTY_UPRAVLENIE_TSVETOM_RGB' => 'Управление цветом (RGB)',
    'PROPERTY_DIMMIRUEMYY_AYA' => 'Диммируемый (-ая)',
    'PROPERTY_IMPULSNO_ZAZHIGAYUSHCHEE_USTROYSTVO_IZU' => 'Импульсно-зажигающее устройство (ИЗУ)',
    'PROPERTY_REZHIM_AVARIYNOGO_OSVESHCHENIYA' => 'Режим аварийного освещения',
    'PROPERTY_VID_RASTRA_RESHETKI' => 'Вид растра/решетки',
    'PROPERTY_POVOROTNYY_VYDVIZHNOY' => 'Поворотный/выдвижной',
    'PROPERTY_SVETORASPREDELENIE' => 'Светораспределение',
    'PROPERTY_IZU_V_KOMPLEKTE' => 'ИЗУ в комплекте',
    'PROPERTY_PRA_V_KOMPLEKTE' => 'ПРА в комплекте',
    'PROPERTY_TIP_PUSKOREGULIRUYUSHCHEGO_APPARATA_PRA' => 'Тип пускорегулирующего аппарата (ПРА)',
    'PROPERTY_PODSVETKA' => 'Подсветка',
    'PROPERTY_S_LAMP_V_KOMPLEKTE' => 'С ламп. в комплекте',
    'PROPERTY_KOLICHESTVO_LAMP_ISTOCHNIKOV_SVETA' => 'Количество ламп (источников света)',
    'PROPERTY_TSOKOL_PATRON_LAMPY' => 'Цоколь (патрон) лампы',
    'PROPERTY_TIP_LAMPY' => 'Тип лампы',
    'PROPERTY_DIAMETR_MONTAZHNYY_VSTRAIV_MM' => 'Диаметр монтажный (встраив.)',
    'PROPERTY_TSVET_RASSEIVATELYA_KRYSHKI' => 'Цвет рассеивателя/крышки',
    'PROPERTY_MATERIAL_RASSEIVATELYA_KRYSHKI' => 'Материал рассеивателя/крышки',
    'PROPERTY_SHIRINA_MM' => 'Ширина',
    'PROPERTY_TIP_SVETILNIKA' => 'Тип светильника',
    'PROPERTY_VYSOTA_MM' => 'Высота',
    'PROPERTY_TIP_KOMPONENTA' => 'Тип компонента',
    'PROPERTY_GLUBINA_USTANOVOCHNAYA_VSTRAIV_MM' => 'Глубина установочная (встраив.)',
    'PROPERTY_UGOL_SVETOVOGO_PUCHKA' => 'Угол светового пучка',
    'PROPERTY_TIP_POVERKHNOSTI' => 'Тип поверхности',
    'PROPERTY_KLASS_ENERGOEFFEKTIVNOSTI' => 'Класс энергоэффективности',
    'PROPERTY_MATERIAL_RASTRA_RESHETKI' => 'Материал растра/решетки',
    'PROPERTY_KOEFFITSIENT_MOSHCHNOSTI' => 'Коэффициент мощности',
    'PROPERTY_PREDELNAYA_TEMPERATURA_C' => 'Предельная температура',
    'PROPERTY_TSVETOVOY_KOD_SVETA' => 'Цветовой код света',
    'PROPERTY_KLIMATICHESKOE_ISPOLNENIE_I_KATEGORIYA_RAZMESHCHEN' => 'Климатическое исполнение и категория размещения',
    'PROPERTY_TIP_NAPRYAZHENIYA' => 'Тип напряжения',
    'PROPERTY_TSVET' => 'Цвет',
    'PROPERTY_MOSHCHNOST_ISTOCHNIKOV_SVETA_NA_1_METR_POGONNYY_VT' => 'Мощность источников света на 1 метр погонный',
    'PROPERTY_MODEL_ISPOLNENIE' => 'Модель/исполнение',
    'PROPERTY_VYKHOD_NAPRYAZHENIE_V' => 'Выход. напряжение',
    'PROPERTY_VYKHOD_MOSHCHNOST_VT' => 'Выход. мощность',
    'PROPERTY_NOMIN_NAPRYAZHENIE_V_1' => 'Номин. напряжение',
    'PROPERTY_KOEFFITSIENT_PULSATSII_SVETOVOGO_POTOKA_NE_BOLEE_' => 'Коэффициент пульсации светового потока',
    'PROPERTY_KOLICHESTVO_ISTOCHNIKOV_SVETA_NA_1_METR_POGONNYY' => 'Количество источников света на 1 метр погонный',
    'PROPERTY_TIP_IZDELIYA_KOMPONENTA' => 'Тип изделия/компонента',
    'PROPERTY_RADIUS_DEYSTVIYA_DATCHIKA_DVIZHENIYA_M' => 'Радиус действия датчика движения',
    'PROPERTY_S_DATCHIKOM_DVIZHENIYA' => 'С датчиком движения',
    'PROPERTY_KOLBA_LAMPY_IZ_CHERNOGO_STEKLA_MYAGKIY_UF' => 'Колба лампы из черного стекла (мягкий УФ)',
    'PROPERTY_CHASTOTA_SETI_PEREMENNOGO_TOKA_GTS' => 'Частота сети переменного тока',
    'PROPERTY_OBSHCH_DLINA_MM' => 'Общ. длина',
    'PROPERTY_SPETSIALNOE_PRIMENENIE' => 'Специальное применение',
    'PROPERTY_VSTROENNYY_FOTOSENSOR' => 'Встроенный фотосенсор',
    'PROPERTY_MATERIAL' => 'Материал',
    'PROPERTY_TSVETNOST_SVETA_PO_STANDARTU_EN_12464_1' => 'Цветность света по стандарту EN 12464-1',
    'edit1_csection1' => 'Виды упаковки',
    'edit1_csection2' => 'Индивидуальная упаковка',
    'PROPERTY_2571' => 'Индивидуальная упаковка: количество',
    'PROPERTY_INDIVIDUAL_PACKAGE_WEIGHT' => 'Индивидуальная упаковка: вес',
    'PROPERTY_INDIVIDUAL_PACKAGE_HEIGHT' => 'Индивидуальная упаковка: высота',
    'PROPERTY_INDIVIDUAL_PACKAGE_LENGTH' => 'Индивидуальная упаковка: длина',
    'PROPERTY_INDIVIDUAL_PACKAGE_VOLUME' => 'Индивидуальная упаковка: объем',
    'PROPERTY_INDIVIDUAL_PACKAGE_WIDTH' => 'Индивидуальная упаковка: ширина',
    'PROPERTY_INDIVIDUAL_PACKAGE_BARCODE' => 'Индивидуальная упаковка: штрихкод',
    'edit1_csection4' => 'Групповая упаковка',
    'PROPERTY_GROUP_PACKAGE_QUANTITY' => 'Групповая упаковка: количество',
    'PROPERTY_GROUP_PACKAGE_WEIGHT' => 'Групповая упаковка: вес',
    'PROPERTY_GROUP_PACKAGE_HEIGHT' => 'Групповая упаковка: высота',
    'PROPERTY_GROUP_PACKAGE_LENGTH' => 'Групповая упаковка: длина',
    'PROPERTY_GROUP_PACKAGE_VOLUME' => 'Групповая упаковка: объем',
    'PROPERTY_GROUP_PACKAGE_WIDTH' => 'Групповая упаковка: ширина',
    'PROPERTY_GROUP_PACKAGE_BARCODE' => 'Групповая упаковка: штрихкод',
    'edit1_csection6' => 'Транспортная упаковка',
    'PROPERTY_TRANSPORT_PACKAGE_QUANTITY' => 'Транспортная упаковка: количество',
    'PROPERTY_TRANSPORT_PACKAGE_WEIGHT' => 'Транспортная упаковка: вес',
    'PROPERTY_TRANSPORT_PACKAGE_HEIGHT' => 'Транспортная упаковка: высота',
    'PROPERTY_TRANSPORT_PACKAGE_LENGTH' => 'Транспортная упаковка: длина',
    'PROPERTY_TRANSPORT_PACKAGE_VOLUME' => 'Транспортная упаковка: объем',
    'PROPERTY_TRANSPORT_PACKAGE_WIDTH' => 'Транспортная упаковка: ширина',
    'PROPERTY_TRANSPORT_PACKAGE_BARCODE' => 'Транспортная упаковка: штрихкод',
  ),
  'Анонс|edit5' => 
  array (
    'PREVIEW_PICTURE' => 'Картинка для анонса',
  ),
  'Подробно|edit6' => 
  array (
    'DETAIL_PICTURE' => 'Детальная картинка',
    'DETAIL_TEXT' => 'Детальное описание',
  ),
  'SEO|edit14' => 
  array (
    'IPROPERTY_TEMPLATES_ELEMENT_META_TITLE' => 'Шаблон META TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_META_KEYWORDS' => 'Шаблон META KEYWORDS',
    'IPROPERTY_TEMPLATES_ELEMENT_META_DESCRIPTION' => 'Шаблон META DESCRIPTION',
    'IPROPERTY_TEMPLATES_ELEMENT_PAGE_TITLE' => 'Заголовок элемента',
    'IPROPERTY_TEMPLATES_ELEMENTS_PREVIEW_PICTURE' => 'Настройки для картинок анонса элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_ELEMENTS_DETAIL_PICTURE' => 'Настройки для детальных картинок элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'SEO_ADDITIONAL' => 'Дополнительно',
    'TAGS' => 'Теги',
  ),
  'Группа|edit2' => 
  array (
    'SECTIONS' => 'Разделы',
  ),
  'Торговый каталог|edit10' => 
  array (
    'CATALOG' => 'Торговый каталог',
  ),
));
        $helper->UserOptions()->saveSectionForm($iblockId, array (
  'Раздел|edit1' => 
  array (
    'ID' => 'ID',
    'DATE_CREATE' => 'Создан',
    'TIMESTAMP_X' => 'Изменен',
    'ACTIVE' => 'Раздел активен',
    'IBLOCK_SECTION_ID' => 'Родительский раздел',
    'NAME' => 'Название',
    'CODE' => 'Символьный код',
    'PICTURE' => 'Изображение',
    'UF_TITLE' => 'Seo-заголовок',
    'UF_BANNER' => 'Статичный баннер',
    'UF_BANNER_LINK' => 'Ссылка на статичный баннер',
    'UF_IS_NEW' => 'NEW',
    'DESCRIPTION' => 'Описание',
    'UF_VIDEO_REVIEW_SRC' => 'Ссылка на видео-обзор',
    'UF_SECTION_REVIEW' => 'Ссылка на видео-обзор',
  ),
  'SEO|edit5' => 
  array (
    'IPROPERTY_TEMPLATES_SECTION' => 'Настройки для разделов',
    'IPROPERTY_TEMPLATES_SECTION_META_TITLE' => 'Шаблон META TITLE',
    'IPROPERTY_TEMPLATES_SECTION_META_KEYWORDS' => 'Шаблон META KEYWORDS',
    'IPROPERTY_TEMPLATES_SECTION_META_DESCRIPTION' => 'Шаблон META DESCRIPTION',
    'IPROPERTY_TEMPLATES_SECTION_PAGE_TITLE' => 'Заголовок раздела',
    'IPROPERTY_TEMPLATES_ELEMENT' => 'Настройки для элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_META_TITLE' => 'Шаблон META TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_META_KEYWORDS' => 'Шаблон META KEYWORDS',
    'IPROPERTY_TEMPLATES_ELEMENT_META_DESCRIPTION' => 'Шаблон META DESCRIPTION',
    'IPROPERTY_TEMPLATES_ELEMENT_PAGE_TITLE' => 'Заголовок товара',
    'IPROPERTY_TEMPLATES_SECTIONS_PICTURE' => 'Настройки для изображений разделов',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_SECTIONS_DETAIL_PICTURE' => 'Настройки для детальных картинок разделов',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_ELEMENTS_PREVIEW_PICTURE' => 'Настройки для картинок анонса элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_ELEMENTS_DETAIL_PICTURE' => 'Настройки для детальных картинок элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_MANAGEMENT' => 'Управление',
    'IPROPERTY_CLEAR_VALUES' => 'Очистить кеш вычисленных значений',
  ),
  'Дополнительно|edit2' => 
  array (
    'SORT' => 'Сортировка',
    'DETAIL_PICTURE' => 'Детальная картинка',
  ),
  'Доп. поля|user_fields_tab' => 
  array (
    'USER_FIELDS_ADD' => 'Добавить пользовательское свойство',
    'UF_IBLOCK_PROPERTIES' => 'Свойства для раздела',
  ),
  'Свойства элементов|edit4' => 
  array (
    'SECTION_PROPERTY' => 'Свойства элементов',
  ),
  'Доступ|edit3' => 
  array (
    'RIGHTS' => 'Права доступа к разделу',
  ),
));
    $helper->UserOptions()->saveElementGrid($iblockId, array (
  'views' => 
  array (
    'default' => 
    array (
      'name' => NULL,
      'columns' => 
      array (
        0 => 'CATALOG_TYPE',
        1 => 'NAME',
        2 => 'SECTIONS',
        3 => 'ACTIVE',
        4 => 'PROPERTY_AKTIVNOST',
        5 => 'SORT',
        6 => 'DATE_CREATE',
        7 => 'CODE',
        8 => 'TIMESTAMP_X',
        9 => 'EXTERNAL_ID',
        10 => 'ID',
        11 => 'PROPERTY_LINKS_IMG_360',
        12 => 'PROPERTY_CML2_ARTICLE',
        13 => 'CATALOG_AVAILABLE',
        14 => 'CATALOG_PURCHASING_PRICE',
        15 => 'CATALOG_GROUP_3',
        16 => 'CATALOG_GROUP_4',
        17 => 'CATALOG_GROUP_5',
        18 => 'CATALOG_GROUP_6',
        19 => 'CATALOG_GROUP_7',
        20 => 'CATALOG_GROUP_8',
      ),
      'sort_by' => NULL,
      'sort_order' => NULL,
      'page_size' => 20,
      'saved_filter' => NULL,
      'custom_names' => 
      array (
        'PROPERTY_2546' => 'Youtube видео',
      ),
      'columns_sizes' => 
      array (
        'expand' => 1,
        'columns' => 
        array (
        ),
      ),
      'sticked_columns' => 
      array (
      ),
      'last_sort_by' => 'PROPERTY_2565',
      'last_sort_order' => 'desc',
    ),
  ),
  'filters' => 
  array (
  ),
  'current_view' => 'default',
));
    $helper->UserOptions()->saveSectionGrid($iblockId, array (
  'views' => 
  array (
    'default' => 
    array (
      'columns' => 
      array (
        0 => 'NAME',
        1 => 'ACTIVE',
        2 => 'SORT',
        3 => 'CODE',
        4 => 'XML_ID',
        5 => 'ELEMENT_CNT',
        6 => 'TIMESTAMP_X',
        7 => 'DATE_CREATE',
        8 => 'ID',
        9 => 'UF_TITLE',
      ),
      'columns_sizes' => 
      array (
        'expand' => 1,
        'columns' => 
        array (
        ),
      ),
      'sticked_columns' => 
      array (
      ),
      'custom_names' => NULL,
      'page_size' => 500,
      'last_sort_by' => 'sort',
      'last_sort_order' => 'asc',
    ),
  ),
  'filters' => 
  array (
  ),
  'current_view' => 'default',
));

    }

    public function down()
    {
        //your code ...
    }
}
